# Generated by Django 6.0.7 on 2026-09-01 19:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=120, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=120, verbose_name='Name (Arabic)')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ShopSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(blank=True, help_text='Digits only, with country code, e.g. 201234567890', max_length=32)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address_en', models.CharField(blank=True, max_length=255, verbose_name='Address (English)')),
                ('address_ar', models.CharField(blank=True, max_length=255, verbose_name='Address (Arabic)')),
                ('hours_en', models.CharField(blank=True, max_length=255, verbose_name='Opening hours (English)')),
                ('hours_ar', models.CharField(blank=True, max_length=255, verbose_name='Opening hours (Arabic)')),
                ('instagram_url', models.URLField(blank=True)),
                ('hero_image', models.ImageField(blank=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'shop settings',
                'verbose_name_plural': 'shop settings',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=150, verbose_name='Name (English)')),
                ('name_ar', models.CharField(blank=True, max_length=150, verbose_name='Name (Arabic)')),
                ('description_en', models.TextField(blank=True, verbose_name='Description (English)')),
                ('description_ar', models.TextField(blank=True, verbose_name='Description (Arabic)')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/')),
                ('is_available', models.BooleanField(default=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='menu.category')),
            ],
            options={
                'ordering': ['category__display_order', 'category__id', 'display_order', 'id'],
            },
        ),
    ]
